// Test to generate TypeScript type definitions
// Run with: cargo test -p orcs-core --test generate_typescript_types -- --nocapture

use orcs_core::schema::{
    ConversationModeType, ExecutionModelType, PresetSourceType, SessionType, TalkStyleType,
    TaskStatus, TaskType,
};
use orcs_core::session::{
    AppMode, AutoChatConfig, ContextMode, ConversationMessage, ConversationMode, ErrorSeverity,
    MessageMetadata, MessageRole, Plan, SandboxState, StopCondition, SystemEventType,
};
use orcs_core::state::model::{AppState, OpenTab};
use orcs_core::workspace::{ProjectContext, TempFile, UploadedFile, Workspace, WorkspaceResources};
use schema_bridge::SchemaBridge;
use std::fs;
use std::path::Path;

#[test]
fn generate_typescript_types() {
    let output_dir = Path::new("../../orcs-desktop/src/bindings");
    fs::create_dir_all(output_dir).expect("Failed to create bindings directory");

    let mut types = Vec::new();

    // Core types
    types.push(("TalkStyleType", TalkStyleType::to_ts()));
    types.push(("ExecutionModelType", ExecutionModelType::to_ts()));
    types.push(("ConversationModeType", ConversationModeType::to_ts()));
    types.push(("PresetSourceType", PresetSourceType::to_ts()));

    // App State types
    types.push(("AppState", AppState::to_ts()));
    types.push(("OpenTab", OpenTab::to_ts()));

    // Message types
    types.push(("MessageRole", MessageRole::to_ts()));
    types.push(("SystemEventType", SystemEventType::to_ts()));
    types.push(("ErrorSeverity", ErrorSeverity::to_ts()));
    types.push(("MessageMetadata", MessageMetadata::to_ts()));
    types.push(("ConversationMessage", ConversationMessage::to_ts()));

    // App Mode types
    types.push(("Plan", Plan::to_ts()));
    types.push(("AppMode", AppMode::to_ts()));
    types.push(("ConversationMode", ConversationMode::to_ts()));

    // Session types
    types.push(("AutoChatConfig", AutoChatConfig::to_ts()));
    types.push(("StopCondition", StopCondition::to_ts()));
    types.push(("SandboxState", SandboxState::to_ts()));
    types.push(("ContextMode", ContextMode::to_ts()));
    types.push(("SessionType", SessionType::to_ts()));

    // Task types
    types.push(("TaskStatus", TaskStatus::to_ts()));
    types.push(("TaskType", TaskType::to_ts()));

    // Workspace types
    types.push(("Workspace", Workspace::to_ts()));
    types.push(("WorkspaceResources", WorkspaceResources::to_ts()));
    types.push(("UploadedFile", UploadedFile::to_ts()));
    types.push(("ProjectContext", ProjectContext::to_ts()));
    types.push(("TempFile", TempFile::to_ts()));

    // Write to file
    let mut content =
        String::from("// Auto-generated TypeScript types from Rust using schema-bridge\n");
    content.push_str("// DO NOT EDIT MANUALLY\n");
    content
        .push_str("// Generated by: cargo test -p orcs-core --test generate_typescript_types\n\n");

    for (name, ts_def) in &types {
        content.push_str(&format!("export type {} = {};\n\n", name, ts_def));
        println!("{}: {}", name, ts_def);
    }

    let output_file = output_dir.join("generated.ts");
    fs::write(&output_file, &content).expect("Failed to write TypeScript types");

    println!("\n✅ TypeScript types generated at: {:?}", output_file);
    println!("Total types generated: {}", types.len());
}
