use std::env;
use std::path::PathBuf;

fn main() {
    // Get the workspace root (2 levels up from crates/orcs-core)
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let manifest_path = PathBuf::from(&manifest_dir);
    let workspace_root = manifest_path
        .parent()
        .and_then(|p| p.parent())
        .expect("Failed to find workspace root");

    // Target path: orcs-desktop/src/types/generated/schema.ts
    let output_path = workspace_root
        .join("orcs-desktop")
        .join("src")
        .join("types")
        .join("generated");

    // Ensure the directory exists
    std::fs::create_dir_all(&output_path).expect("Failed to create output directory");

    let output_file = output_path.join("schema.ts");

    // Generate TypeScript type definitions
    let types = vec![
        ("TalkStyleType", generate_talk_style_type()),
        ("ExecutionModelType", generate_execution_model_type()),
        ("ConversationModeType", generate_conversation_mode_type()),
        ("PresetSourceType", generate_preset_source_type()),
    ];

    let mut content = String::new();
    content.push_str("// This file is auto-generated by schema-bridge during build\n");
    content.push_str("// Do not edit manually - changes will be overwritten\n");
    content.push_str("// Generated from: crates/orcs-core/src/schema.rs\n\n");

    for (name, ts_def) in types {
        content.push_str(&format!("export type {} = {};\n\n", name, ts_def));
    }

    std::fs::write(&output_file, content).expect("Failed to write TypeScript file");

    println!("cargo:rerun-if-changed=src/schema.rs");
    println!(
        "cargo:warning=Generated TypeScript types at: {}",
        output_file.display()
    );
}

fn generate_talk_style_type() -> String {
    "'Brainstorm' | 'Casual' | 'DecisionMaking' | 'Debate' | 'ProblemSolving' | 'Review' | 'Planning'".to_string()
}

fn generate_execution_model_type() -> String {
    "'broadcast' | 'sequential'".to_string()
}

fn generate_conversation_mode_type() -> String {
    "'normal' | 'concise' | 'brief' | 'discussion'".to_string()
}

fn generate_preset_source_type() -> String {
    "'system' | 'user'".to_string()
}
