// Auto-generated TypeScript types from Rust using schema-bridge
// DO NOT EDIT MANUALLY
// Generated by: orcs schema generate

export type TalkStyleType = 'Brainstorm' | 'Casual' | 'DecisionMaking' | 'Debate' | 'ProblemSolving' | 'Review' | 'Planning';

export type ExecutionModelType = 'broadcast' | 'sequential';

export type ConversationModeType = 'detailed' | 'normal' | 'concise' | 'brief' | 'discussion';

export type PresetSourceType = 'system' | 'user';

export type AppState = { lastSelectedWorkspaceId: string | null; defaultWorkspaceId: string | null; activeSessionId: string | null; openTabs: { id: string; sessionId: string; workspaceId: string; lastAccessedAt: number; order: number; }[]; activeTabId: string | null; };

export type OpenTab = { id: string; sessionId: string; workspaceId: string; lastAccessedAt: number; order: number; };

export type MessageRole = 'User' | 'Assistant' | 'System';

export type SystemEventType = 'participant_joined' | 'participant_left' | 'execution_strategy_changed' | 'mode_changed' | 'workspace_switched' | 'notification';

export type ErrorSeverity = 'critical' | 'warning' | 'info';

export type MessageMetadata = { system_event_type: 'participant_joined' | 'participant_left' | 'execution_strategy_changed' | 'mode_changed' | 'workspace_switched' | 'notification' | null; error_severity: 'critical' | 'warning' | 'info' | null; system_message_type: string | null; include_in_dialogue: boolean; };

export type ConversationMessage = { role: 'User' | 'Assistant' | 'System'; content: string; timestamp: string; metadata: { system_event_type: 'participant_joined' | 'participant_left' | 'execution_strategy_changed' | 'mode_changed' | 'workspace_switched' | 'notification' | null; error_severity: 'critical' | 'warning' | 'info' | null; system_message_type: string | null; include_in_dialogue: boolean; }; attachments: string[]; };

export type Plan = { steps: string[]; };

export type AppMode = 'Idle' | 'AwaitingConfirmation';

export type ConversationMode = 'detailed' | 'normal' | 'concise' | 'brief' | 'discussion';

export type AutoChatConfig = { max_iterations: number; stop_condition: 'iteration_count' | 'user_interrupt'; web_search_enabled: boolean; };

export type StopCondition = 'iteration_count' | 'user_interrupt';

export type Workspace = { id: string; name: string; rootPath: string; workspaceDir: string; resources: { uploaded_files: { id: string; name: string; path: string; mime_type: string; size: number; uploaded_at: number; session_id: string | null; message_timestamp: string | null; author: string | null; is_archived: boolean; is_favorite: boolean; sort_order: number | null; }[]; temp_files: { id: string; path: string; purpose: string; created_at: number; auto_delete: boolean; }[]; }; projectContext: { languages: string[]; build_system: string | null; description: string | null; repository_url: string | null; metadata: Record<string, string>; }; lastAccessed: number; isFavorite: boolean; lastActiveSessionId: string | null; };

export type WorkspaceResources = { uploaded_files: { id: string; name: string; path: string; mime_type: string; size: number; uploaded_at: number; session_id: string | null; message_timestamp: string | null; author: string | null; is_archived: boolean; is_favorite: boolean; sort_order: number | null; }[]; temp_files: { id: string; path: string; purpose: string; created_at: number; auto_delete: boolean; }[]; };

export type UploadedFile = { id: string; name: string; path: string; mime_type: string; size: number; uploaded_at: number; session_id: string | null; message_timestamp: string | null; author: string | null; is_archived: boolean; is_favorite: boolean; sort_order: number | null; };

export type ProjectContext = { languages: string[]; build_system: string | null; description: string | null; repository_url: string | null; metadata: Record<string, string>; };

export type TempFile = { id: string; path: string; purpose: string; created_at: number; auto_delete: boolean; };

export type SessionType = { id: string; title: string; createdAt: string; updatedAt: string; currentPersonaId: string; workspaceId: string; activeParticipantIds: string[]; executionStrategy: 'broadcast' | 'sequential'; participants: Record<string, string>; participantIcons: Record<string, string>; participantColors: Record<string, string>; participantBackends: Record<string, string>; participantModels: Record<string, string>; conversationMode: 'detailed' | 'normal' | 'concise' | 'brief' | 'discussion'; talkStyle: 'Brainstorm' | 'Casual' | 'DecisionMaking' | 'Debate' | 'ProblemSolving' | 'Review' | 'Planning' | null; isFavorite: boolean; isArchived: boolean; sortOrder: number | null; isMuted: boolean; };

