// Auto-generated TypeScript types from Rust using schema-bridge
// DO NOT EDIT MANUALLY
// Generated by: orcs schema generate

export type TalkStyleType = 'Brainstorm' | 'Casual' | 'DecisionMaking' | 'Debate' | 'ProblemSolving' | 'Review' | 'Planning';

export type ExecutionModelType = 'broadcast' | 'sequential' | 'mentioned';

export type ConversationModeType = 'detailed' | 'normal' | 'concise' | 'brief' | 'discussion';

export type PresetSourceType = 'system' | 'user';

export type AppState = { lastSelectedWorkspaceId: string | null; defaultWorkspaceId: string | null; activeSessionId: string | null; openTabs: { id: string; sessionId: string; workspaceId: string; lastAccessedAt: number; order: number; }[]; activeTabId: string | null; };

export type OpenTab = { id: string; sessionId: string; workspaceId: string; lastAccessedAt: number; order: number; };

export type MessageRole = 'User' | 'Assistant' | 'System';

export type SystemEventType = 'participant_joined' | 'participant_left' | 'execution_strategy_changed' | 'mode_changed' | 'workspace_switched' | 'notification';

export type ErrorSeverity = 'critical' | 'warning' | 'info';

export type MessageMetadata = { systemEventType: 'participant_joined' | 'participant_left' | 'execution_strategy_changed' | 'mode_changed' | 'workspace_switched' | 'notification' | null; errorSeverity: 'critical' | 'warning' | 'info' | null; systemMessageType: string | null; includeInDialogue: boolean; };

export type ConversationMessage = { role: 'User' | 'Assistant' | 'System'; content: string; timestamp: string; metadata: { systemEventType: 'participant_joined' | 'participant_left' | 'execution_strategy_changed' | 'mode_changed' | 'workspace_switched' | 'notification' | null; errorSeverity: 'critical' | 'warning' | 'info' | null; systemMessageType: string | null; includeInDialogue: boolean; }; attachments: string[]; };

export type Plan = { steps: string[]; };

export type AppMode = 'Idle' | 'AwaitingConfirmation';

export type ConversationMode = 'detailed' | 'normal' | 'concise' | 'brief' | 'discussion';

export type AutoChatConfig = { max_iterations: number; stop_condition: 'iteration_count' | 'user_interrupt'; web_search_enabled: boolean; };

export type StopCondition = 'iteration_count' | 'user_interrupt';

export type Workspace = { id: string; name: string; rootPath: string; workspaceDir: string; resources: { uploadedFiles: { id: string; name: string; path: string; mimeType: string; size: number; uploadedAt: number; sessionId: string | null; messageTimestamp: string | null; author: string | null; isArchived: boolean; isFavorite: boolean; sortOrder: number | null; }[]; tempFiles: { id: string; path: string; purpose: string; createdAt: number; autoDelete: boolean; }[]; }; projectContext: { languages: string[]; buildSystem: string | null; description: string | null; repositoryUrl: string | null; metadata: Record<string, string>; }; lastAccessed: number; isFavorite: boolean; lastActiveSessionId: string | null; };

export type WorkspaceResources = { uploadedFiles: { id: string; name: string; path: string; mimeType: string; size: number; uploadedAt: number; sessionId: string | null; messageTimestamp: string | null; author: string | null; isArchived: boolean; isFavorite: boolean; sortOrder: number | null; }[]; tempFiles: { id: string; path: string; purpose: string; createdAt: number; autoDelete: boolean; }[]; };

export type UploadedFile = { id: string; name: string; path: string; mimeType: string; size: number; uploadedAt: number; sessionId: string | null; messageTimestamp: string | null; author: string | null; isArchived: boolean; isFavorite: boolean; sortOrder: number | null; };

export type ProjectContext = { languages: string[]; buildSystem: string | null; description: string | null; repositoryUrl: string | null; metadata: Record<string, string>; };

export type TempFile = { id: string; path: string; purpose: string; createdAt: number; autoDelete: boolean; };

export type SessionType = { id: string; title: string; createdAt: string; updatedAt: string; currentPersonaId: string; workspaceId: string; activeParticipantIds: string[]; executionStrategy: 'broadcast' | 'sequential' | 'mentioned'; participants: Record<string, string>; participantIcons: Record<string, string>; participantColors: Record<string, string>; participantBackends: Record<string, string>; participantModels: Record<string, string>; conversationMode: 'detailed' | 'normal' | 'concise' | 'brief' | 'discussion'; talkStyle: 'Brainstorm' | 'Casual' | 'DecisionMaking' | 'Debate' | 'ProblemSolving' | 'Review' | 'Planning' | null; isFavorite: boolean; isArchived: boolean; sortOrder: number | null; isMuted: boolean; };

export type TaskType = { id: string; sessionId: string; title: string; description: string; status: 'Pending' | 'Running' | 'Completed' | 'Failed'; createdAt: string; updatedAt: string; completedAt: string | null; stepsExecuted: number; stepsSkipped: number; contextKeys: number; error: string | null; result: string | null; };

export type TaskStatus = 'Pending' | 'Running' | 'Completed' | 'Failed';

